package com.example.foodrescue.orderservice.configuration

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration
import org.springframework.scheduling.annotation.EnableScheduling

@Configuration
@EnableScheduling
@EnableConfigurationProperties(OrderSchedulerProperties::class)
class OrderSchedulerConfiguration
